
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module C5G_sevenseg(

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================

sevenseg u0_sevenseg
(
   .bin           (SW[3:0]), 
   .hex           (),
   .hexn          (HEX0)
);

sevenseg u1_sevenseg
(
   .bin           (SW[7:4]), 
   .hex           (),
   .hexn          (HEX1)
);

assign HEX2 = 'b0;
assign HEX3 = 'b0;


endmodule
